### PR TITLE
Wordsmithing of introduction.

### PR DESCRIPTION
**Pull request by susanatx**
-Combined two one-sentence paragraphs into one and attempted a reword of the last bullet. "Coordination between" the three topics doesn't make sense to me. What are they coordinating with each other?

### CODE REVIEW

**Comment by lakeen** [comment]
In most situations, such as when designing and developing websites and applications, it is most effective to address them together.

I would also shorten this sentence to:

"When designing and developing websites and applications, it is most effective to address them together."

**Comment by shawna-slh** [comment]
> Combined two one-sentence paragraphs into one

[low] I slightly prefer leaving them as separate paragraphs so the second point doesn't get lost -- but it's only slight and I'm OK with combining them if others feel strongly.

> From "* encourages increased coordination between accessibility, usability, and inclusion"
to "* encourages increased coordination across accessibility, usability, and inclusion practices.

[low] "practices" limits it though -- we also want coordination on research, training, etc. I don't feel strongly, and I guess would be OK with this change if no one comes up with a better way to address it.

**Comment by shawna-slh** [comment]
> In most situations, such as when designing and developing websites and applications, it is most effective to address them together.
-->
"When designing and developing websites and applications, it is most effective to address them together."

"such as..." was just one example. There are other situations, such as training, when it is most effective to address them together.

**Comment by susanatx** [comment]
@slhenry 

I'm fine with leaving both as is. In terms of the "such as..." sentence, I was trying to streamline the sentence.

**Comment by bakkenb** [comment]
Throwing a monkey wrench in here...

[mild - medium / editors discretion] 
When I read it, I was thinking the same as Susan about combining some of the one sentence paragraphs. However, I liked combining the first and second (to be the first paragraph) and leaving the third as is. 

Before:

> Accessibility, usability, and inclusive design are closely related. Their goals, approaches, and guidelines overlap significantly.
>
> 
> In most situations, such as when designing and developing websites and applications, it is most effective to address them together.
> 
> There are a few situations when it's important to focus specifically on one aspect, such as when addressing discrimination against people with disabilities and when defining specific accessibility standards.

After:

> Accessibility, usability, and inclusive design are closely related. Their goals, approaches, and guidelines overlap significantly. When designing and developing websites and applications, it is most effective to address them together.
> 
> There are a few situations when it's important to focus specifically on one aspect, such as when addressing discrimination against people with disabilities and when defining specific accessibility standards.

**Comment by lakeen** [comment]
+1

**Pull request closed without merging**
