### PR TITLE
A11y & Usability and A11y & Inclusion sections

### PR DESCRIPTION
**Pull request by susanatx**
-Question on list of situations under A&U heading - what is meant by "in an emergency"? 
-Moved last sentence under last paragraph in Usability into its preceding paragraph.
-A&I heading, cut use of "people with disabilities" from three times in the second paragraph after the bulleted list to just one. I don't think using pronouns will make the reader forget who we're talking about and helps cut down on wordiness.

### CODE REVIEW

**Comment by lakeen** [comment]
"In defining accessibility requirements, care is usually taken to not include aspects that impact all people similarly, and only include aspects that put person with a disability is at a disadvantage relative to a person without a disability."

Suggest:
When defining accessibility requirements, do not include aspects that impact all people similarly, only include aspects that put a person with a disability at a disadvantage relative to a person without a disability.

**Comment by bakkenb** [comment]
+1 to @lakeen edit

[strong] That sentence needs to be reworded

**Comment by susanatx** [comment]
+1

**Comment by shawna-slh** [comment]
All below are [low].

Emergency impacts cognitive ability for interacting with technology -- so this is suppose to show when things we do for cognitive disabilities help people _without_ disabilities. :-)

I'm fine with moving that sentence. I pondered that myself. ;-)

Prefer "describes accessibility benefits to:" rather than "describes accessibility benefits for:".

I'm fine with cutting out the second "people with disabilities" but think we should leave the first one in that paragraph.

**Comment by shawna-slh** [comment]
Re @lakeen edit:

> When defining accessibility requirements, do not include aspects...

The point of this is not to tell them what to do, it's to say what W3C does (and others ought to). I think most people reading this are not defining accessibility requirements themselves.

I suggested a different edit that I think takes care of the same problem with the original wording, but even more simply:

> Accessibility requirements usually do not include aspects...

https://github.com/w3c/wai-inclusion/pull/12/files?short_path=d680e8a#diff-d680e8a854a7cbad6d490c445cba2eba

**Comment by bakkenb** [comment]
+1 to that point @slhenry. I like your update edit.

**Pull request closed without merging**
